spring:
  application:
    name: orders
  config:
    import: "optional:classpath:.env"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_ORDERS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: messages
    encoding: UTF-8
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest #auto-offset-reset: latest
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT}

market-sphere:
  outbox:
    payment-request:
      initial-delay-ms: 5000
      fixed-delay-ms: 5000
    order-paid-messaging:
      initial-delay-ms: 7000
      fixed-delay-ms: 5000
    order-paid-notification:
      initial-delay-ms: 10000
      fixed-delay-ms: 9000

  feign:
    clients:
      products:
        base-url: http://${PRODUCTS_CLIENT_HOST}:${PRODUCTS_CLIENT_PORT}/products
      customers:
        base-url: http://${CUSTOMERS_CLIENT_HOST}:${CUSTOMERS_CLIENT_PORT}/customers
    configs:
      connect-timeout: 5000
      read-timeout: 5000
  kafka:
    config:
      topics:
        paid-orders: ${KAFKA_TOPIC_PAID_ORDERS}
        billed-orders: ${KAFKA_TOPIC_BILLED_ORDERS}
        preparing-shipment-orders: ${KAFKA_TOPIC_PREPARING_SHIPMENT_ORDERS}
        shipped-orders: ${KAFKA_TOPIC_SHIPPED_ORDERS}
  internal-services:
    customers:
      config:
        security:
          api-key: ${CUSTOMERS_SERVICE_API_KEY_FOR_ORDERS}
  external-services:
    banking:
      mock-bank:
        base-url: ${INCOMING...}
        api-key: ${MOCK_BANK_CLIENT_KEY}
        webhook-secret: ${MOCK_BANK_WEBHOOK_SECRET}